version: '3'
services:
  my-next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"  
    environment:
      NEXT_PUBLIC_BASE_URL : https://my-next-app-cherifdv.cloud.okteto.net
      MONGODB_URI : mongodb+srv://wissemslimw:MIfnBRonxlbWiMna@cluster0.i6aej2x.mongodb.net/

